### PR TITLE
Fix bad range check on sideset count in pio.h (closes #96)

### LINKED ISSUE #96: pio.h: sm_config_set_sideset(): bad assertion
pio.h says:

static inline void sm_config_set_sideset(pio_sm_config *c, uint bit_count, bool optional, bool pindirs) {
    assert(bit_count <= 32);
    c->pinctrl = (c->pinctrl & ~PIO_SM0_PINCTRL_SIDESET_COUNT_BITS) |
                 (bit_count << PIO_SM0_PINCTRL_SIDESET_COUNT_LSB);

However, according to RP2040 datasheet, table 397, SIDESET_COUNT occupies bits 31:29, that is only 3 bits, not 5.  That is, the maximum valid value is 7, not 32.

### PR DESCRIPTION
**Pull request by Wren6991**

### CODE REVIEW

File: src/rp2_common/hardware_pio/include/hardware/pio.h [hunk 1]
```diff
@@ -174,12 +174,14 @@ static inline void sm_config_set_sideset_pins(pio_sm_config *c, uint sideset_bas
...
  * \param c Pointer to the configuration structure to modify
- * \param bit_count Number of bits to steal from delay field in the instruction for use of side set
+ * \param bit_count Number of bits to steal from delay field in the instruction for use of side set (max 5)
  * \param optional True if the topmost side set bit is used as a flag for whether to apply side set on that instruction
  * \param pindirs True if the side set affects pin directions rather than values
  */
 static inline void sm_config_set_sideset(pio_sm_config *c, uint bit_count, bool optional, bool pindirs) {
-    assert(bit_count <= 32);
+    assert(bit_count <= 5);
+    if (optional)
```
Comment (kilograham) [inline src/rp2_common/hardware_pio/include/hardware/pio.h:183]: apart from the wrong indentation, i prefer
assert(!optional || bit_count >=1);

**Review by kilograham — CHANGES_REQUESTED** [review]

**Review by kilograham — APPROVED** [review]
