### PR TITLE
Multicore documentation fix

### LINKED ISSUE #2702: Multicore Doorbell Current Core/Other Core Mislabelled
In both the SDK, and the SDK reference, the multicore doorbell check functions have been incorrectly documented as checking the opposite core than it should be checking. 

https://github.com/raspberrypi/pico-sdk/blob/a1438dff1d38bd9c65dbd693f0e5db4b9ae91779/src/rp2_common/pico_multicore/include/pico/multicore.h#L380-L396

### PR DESCRIPTION
**Pull request by madh4tter**
Fixes #2702

### CODE REVIEW

File: src/rp2_common/pico_multicore/include/pico/multicore.h [hunk 1]
```diff
@@ -377,7 +377,7 @@ static inline void multicore_doorbell_clear_current_core(uint doorbell_num) {
     sio_hw->doorbell_in_clr = 1u << doorbell_num;
 }
 
-/*! \brief Determine if the given doorbell is active on the other core
+/*! \brief Determine if the given doorbell is active on the this core
```
Comment (lurch) [inline src/rp2_common/pico_multicore/include/pico/multicore.h]:
```suggestion
/*! \brief Determine if the given doorbell is active on this core
```
:wink:

**Review by kilograham — APPROVED** [review]
