### PR TITLE
various floating point fixes

### LINKED ISSUE #2793: Some functions in `pico_float_pico_dcp` do not check the coprocessor state
In the dcp variant of the floating-point library, some functions skipped the DCP wrapper.

Specifically:
https://github.com/raspberrypi/pico-sdk/blob/9c6713a8ed39d7719e353ec35c4124ae4ac05755/src/rp2_common/pico_float/float_aeabi_dcp.S#L187-L188
and
https://github.com/raspberrypi/pico-sdk/blob/9c6713a8ed39d7719e353ec35c4124ae4ac05755/src/rp2_common/pico_float/float_aeabi_dcp.S#L159

### PR DESCRIPTION
**Pull request by kilograham**
- fix issues with and improve tests for dcp conversions of INFINITES to fixed point values
- fixes missing DCP state saves (fix #2793)

### CODE REVIEW

File: test/pico_float_test/custom_double_funcs_test.c [hunk 1]
```diff
@@ -179,6 +181,15 @@ int test() {
...
     test_checki(double2fix(0.0, -16), 0, "double2fix14");
     test_checki(double2fix(-0.0, -16), 0, "double2fix15");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checki(double2fix(u64d.d, 0), INT32_MAX, "double2fix16a");
+    test_checki(double2fix(u64d.d, 1), INT32_MAX, "double2fix16b");
+    test_checki(double2fix(u64d.d, 2), INT32_MAX, "double2fix16c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checki(double2fix(u64d.d, 0), INT32_MIN, "double2fix17d");
+    test_checki(double2fix(u64d.d, 1), INT32_MIN, "double2fix17e");
+    test_checki(double2fix(u64d.d, 2), INT32_MIN, "double2fix17f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0x7fe0000000012345ull;
    test_checki(double2fix(u64d.d, 0), INT32_MAX, "double2fix16a");
    test_checki(double2fix(u64d.d, 1), INT32_MAX, "double2fix16b");
    test_checki(double2fix(u64d.d, 2), INT32_MAX, "double2fix16c");
    u64d.u = 0xffe0000000012345ull;
    test_checki(double2fix(u64d.d, 0), INT32_MIN, "double2fix17a");
    test_checki(double2fix(u64d.d, 1), INT32_MIN, "double2fix17b");
    test_checki(double2fix(u64d.d, 2), INT32_MIN, "double2fix17c");
```
?

File: test/pico_float_test/custom_double_funcs_test.c [hunk 2]
```diff
@@ -189,13 +200,23 @@ int test() {
...
+    test_checku(double2ufix(0.0, -16), 0, "double2ufix14");
+    test_checku(double2ufix(-0.0, -16), 0, "double2ufix15");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checku(double2ufix(u64d.d, 0), UINT32_MAX, "double2ufix16a");
+    test_checku(double2ufix(u64d.d, 1), UINT32_MAX, "double2ufix16b");
+    test_checku(double2ufix(u64d.d, 2), UINT32_MAX, "double2ufix16c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checku(double2ufix(u64d.d, 0), 0, "double2ufix17d");
+    test_checku(double2ufix(u64d.d, 1), 0, "double2ufix17e");
+    test_checku(double2ufix(u64d.d, 2), 0, "double2ufix17f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checku(double2ufix(u64d.d, 0), 0, "double2ufix17a");
    test_checku(double2ufix(u64d.d, 1), 0, "double2ufix17b");
    test_checku(double2ufix(u64d.d, 2), 0, "double2ufix17c");
```

File: test/pico_float_test/custom_double_funcs_test.c [hunk 3]
```diff
@@ -239,6 +262,14 @@ int test() {
...
     u64d.u = 0xc00a000000000000;
     test_checki64(double2fix64(u64d.d, 19), -13ll * (1ll << 17), "double2fix6415k");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checki64(double2fix64(u64d.d, 0), INT64_MAX, "double2fix6416a");
+    test_checki64(double2fix64(u64d.d, 1), INT64_MAX, "double2fix6416b");
+    test_checki64(double2fix64(u64d.d, 2), INT64_MAX, "double2fix6416c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checki64(double2fix64(u64d.d, 0), INT64_MIN, "double2fix6417d");
+    test_checki64(double2fix64(u64d.d, 1), INT64_MIN, "double2fix6417e");
+    test_checki64(double2fix64(u64d.d, 2), INT64_MIN, "double2fix6417f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checki64(double2fix64(u64d.d, 0), INT64_MIN, "double2fix6417a");
    test_checki64(double2fix64(u64d.d, 1), INT64_MIN, "double2fix6417b");
    test_checki64(double2fix64(u64d.d, 2), INT64_MIN, "double2fix6417c");
```

File: test/pico_float_test/custom_double_funcs_test.c [hunk 4]
```diff
@@ -250,11 +281,22 @@ int test() {
...
     test_checki64(double2ufix64(0.0, 16), 0, "double2ufix649");
     test_checki64(double2ufix64(-0.0, 16), 0, "double2ufix6410");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checku64(double2ufix64(u64d.d, 0), UINT64_MAX, "double2ufix6411a");
+    test_checku64(double2ufix64(u64d.d, 1), UINT64_MAX, "double2ufix6411b");
+    test_checku64(double2ufix64(u64d.d, 2), UINT64_MAX, "double2ufix6411c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checku64(double2ufix64(u64d.d, 0), 0, "double2ufix6412d");
+    test_checku64(double2ufix64(u64d.d, 1), 0, "double2ufix6412e");
+    test_checku64(double2ufix64(u64d.d, 2), 0, "double2ufix6412f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checku64(double2ufix64(u64d.d, 0), 0, "double2ufix6412a");
    test_checku64(double2ufix64(u64d.d, 1), 0, "double2ufix6412b");
    test_checku64(double2ufix64(u64d.d, 2), 0, "double2ufix6412c");
```

File: test/pico_float_test/custom_double_funcs_test.c [hunk 5]
```diff
@@ -275,6 +319,14 @@ int test() {
...
     test_checki(double2fix_z(0.0, -16), 0, "double2fix_z12b");
     test_checki(double2fix_z(-0.0, -16), 0, "double2fix_z13b");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checki(double2fix_z(u64d.d, 0), INT32_MAX, "double2fix_z14a");
+    test_checki(double2fix_z(u64d.d, 1), INT32_MAX, "double2fix_z14b");
+    test_checki(double2fix_z(u64d.d, 2), INT32_MAX, "double2fix_z14c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checki(double2fix_z(u64d.d, 0), INT32_MIN, "double2fix_z14d");
+    test_checki(double2fix_z(u64d.d, 1), INT32_MIN, "double2fix_z14e");
+    test_checki(double2fix_z(u64d.d, 2), INT32_MIN, "double2fix_z14f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checki(double2fix_z(u64d.d, 0), INT32_MIN, "double2fix_z15a");
    test_checki(double2fix_z(u64d.d, 1), INT32_MIN, "double2fix_z15b");
    test_checki(double2fix_z(u64d.d, 2), INT32_MIN, "double2fix_z15c");
```
(for consistency)

File: test/pico_float_test/custom_double_funcs_test.c [hunk 6]
```diff
@@ -283,15 +335,25 @@ int test() {
...
     test_checki(double2ufix_z(0.0, -16), 0, "double2ufix_z11");
     test_checki(double2ufix_z(-0.0, -16), 0, "double2ufix_z12");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checku(double2ufix_z(u64d.d, 0), UINT32_MAX, "double2ufix_z13a");
+    test_checku(double2ufix_z(u64d.d, 1), UINT32_MAX, "double2ufix_z13b");
+    test_checku(double2ufix_z(u64d.d, 2), UINT32_MAX, "double2ufix_z13c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checku(double2ufix_z(u64d.d, 0), 0, "double2ufix_z14d");
+    test_checku(double2ufix_z(u64d.d, 1), 0, "double2ufix_z14e");
+    test_checku(double2ufix_z(u64d.d, 2), 0, "double2ufix_z14f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checku(double2ufix_z(u64d.d, 0), 0, "double2ufix_z14a");
    test_checku(double2ufix_z(u64d.d, 1), 0, "double2ufix_z14b");
    test_checku(double2ufix_z(u64d.d, 2), 0, "double2ufix_z14c");
```

File: test/pico_float_test/custom_double_funcs_test.c [hunk 7]
```diff
@@ -333,6 +397,14 @@ int test() {
...
     u64d.u = 0xc00a000000000000;
     test_checki64(double2fix64_z(u64d.d, 19), -13ll * (1ll << 17), "double2fix64_z15k");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checki64(double2fix64_z(u64d.d, 0), INT64_MAX, "double2fix64_z16a");
+    test_checki64(double2fix64_z(u64d.d, 1), INT64_MAX, "double2fix64_z16b");
+    test_checki64(double2fix64_z(u64d.d, 2), INT64_MAX, "double2fix64_z16c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checki64(double2fix64_z(u64d.d, 0), INT64_MIN, "double2fix64_z17d");
+    test_checki64(double2fix64_z(u64d.d, 1), INT64_MIN, "double2fix64_z17e");
+    test_checki64(double2fix64_z(u64d.d, 2), INT64_MIN, "double2fix64_z17f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checki64(double2fix64_z(u64d.d, 0), INT64_MIN, "double2fix64_z17a");
    test_checki64(double2fix64_z(u64d.d, 1), INT64_MIN, "double2fix64_z17b");
    test_checki64(double2fix64_z(u64d.d, 2), INT64_MIN, "double2fix64_z17c");
```

File: test/pico_float_test/custom_double_funcs_test.c (hunk 1 above)
Comment (kilograham) [reply test/pico_float_test/custom_double_funcs_test.c]: oops; i got heavy handed in fixing duplicates somewhere

File: test/pico_float_test/custom_double_funcs_test.c [hunk 8]
```diff
@@ -342,15 +414,25 @@ int test() {
...
+    test_checku64(double2ufix64_z(INFINITY, 0), UINT64_MAX, "double2ufix64_z5e");
+    test_checku64(double2ufix64_z(-INFINITY, 0), 0, "double2ufix64_z5f");
     test_checku64(double2ufix64_z(3.24999, 2), 12, "double2ufix64_z6");
     test_checku64(double2ufix64_z(3.25, 2), 13, "double2ufix64_z7");
-    test_checki64(double2ufix64_z(3.0, -1), 1, "double2fuix64_z8"); // not very useful
-    test_checki64(double2ufix64_z(0.0, 16), 0, "double2ufix64_z9");
-    test_checki64(double2ufix64_z(-0.0, 16), 0, "double2ufix64_z10");
-    test_checki64(double2ufix64_z(0.0, -16), 0, "double2ufix64_z11");
-    test_checki64(double2ufix64_z(-0.0, -16), 0, "double2ufix64_z12");
+    test_checku64(double2ufix64_z(3.0, -1), 1, "double2fuix64_z8"); // not very useful
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    test_checku64(double2ufix64_z(3.0, -1), 1, "double2ufix64_z8"); // not very useful
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 9]
```diff
@@ -301,22 +367,48 @@ int test() {
...
+    test_checku64(float2ufix64_z(65536.0f * 65536.0f * 65536.0f, 16), UINT64_MAX, "float2ufix64_z4b");
     test_checku64(float2ufix64_z(INFINITY, 16), UINT64_MAX, "float2ufix64_z5");
+    test_checku64(float2ufix64_z(-INFINITY, 16), 0, "float2ufix64_z5b");
+    test_checku64(float2ufix64_z(INFINITY, -16), UINT64_MAX, "float2ufix64_z5c");
+    test_checku64(float2ufix64_z(-INFINITY, -16), 0, "float2ufix64_z5d");
+    test_checku64(float2ufix64_z(INFINITY, 0), UINT64_MAX, "float2ufix64_z5e");
+    test_checku64(float2ufix64_z(-INFINITY, 0), 0, "float2ufix64_z5f");
     test_checku64(float2ufix64_z(3.24999f, 2), 12, "float2ufix64_z6");
     test_checku64(float2ufix64_z(3.25f, 2), 13, "float2ufix64_z7");
     test_checki64(float2ufix64_z(3.0f, -1), 1, "float2fuix64_z8"); // not very useful
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    test_checki64(float2ufix64_z(3.0f, -1), 1, "float2ufix64_z8"); // not very useful
```

File: test/pico_float_test/custom_double_funcs_test.c [hunk 10]
```diff
@@ -342,15 +414,25 @@ int test() {
...
+    test_checku64(double2ufix64_z(0.0, -16), 0, "double2ufix64_z11");
+    test_checku64(double2ufix64_z(-0.0, -16), 0, "double2ufix64_z12");
+    u64d.u = 0x7fe0000000012345ull;
+    test_checku64(double2ufix64_z(u64d.d, 0), UINT64_MAX, "double2ufix64_z13a");
+    test_checku64(double2ufix64_z(u64d.d, 1), UINT64_MAX, "double2ufix64_z13b");
+    test_checku64(double2ufix64_z(u64d.d, 2), UINT64_MAX, "double2ufix64_z13c");
+    u64d.u = 0xffe0000000012345ull;
+    test_checku64(double2ufix64_z(u64d.d, 0), 0, "double2ufix64_z13d");
+    test_checku64(double2ufix64_z(u64d.d, 1), 0, "double2ufix64_z13e");
+    test_checku64(double2ufix64_z(u64d.d, 2), 0, "double2ufix64_z13f");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    u64d.u = 0xffe0000000012345ull;
    test_checku64(double2ufix64_z(u64d.d, 0), 0, "double2ufix64_z14a");
    test_checku64(double2ufix64_z(u64d.d, 1), 0, "double2ufix64_z14b");
    test_checku64(double2ufix64_z(u64d.d, 2), 0, "double2ufix64_z14c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 11]
```diff
@@ -216,26 +216,47 @@ int test() {
...
     u32f.u = 0x7f012345;
-    test_checki(float2fix(u32f.f, 1), INT32_MAX, "float2fix12");
+    test_checki(float2fix(u32f.f, 0), INT32_MAX, "float2fix12a");
+    test_checki(float2fix(u32f.f, 1), INT32_MAX, "float2fix12b");
+    test_checki(float2fix(u32f.f, 2), INT32_MAX, "float2fix12c");
     u32f.u = 0xff012345;
-    test_checki(float2fix(u32f.f, 1), INT32_MIN, "float2fix13");
+    test_checki(float2fix(u32f.f, 0), INT32_MIN, "float2fix13d");
+    test_checki(float2fix(u32f.f, 1), INT32_MIN, "float2fix13e");
+    test_checki(float2fix(u32f.f, 2), INT32_MIN, "float2fix13f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    test_checki(float2fix(u32f.f, 0), INT32_MIN, "float2fix13a");
    test_checki(float2fix(u32f.f, 1), INT32_MIN, "float2fix13b");
    test_checki(float2fix(u32f.f, 2), INT32_MIN, "float2fix13c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 12]
```diff
@@ -216,26 +216,47 @@ int test() {
...
     test_checku(float2ufix(3.25f, 2), 13, "float2ufix7");
     test_checku(float2ufix(3.0f, -1), 1, "float2ufix8"); // not very useful
+    u32f.u = 0x7f012345;
+    test_checku(float2ufix(u32f.f, 0), UINT32_MAX, "float2ufix9a");
+    test_checku(float2ufix(u32f.f, 1), UINT32_MAX, "float2ufix9b");
+    test_checku(float2ufix(u32f.f, 2), UINT32_MAX, "float2ufix9c");
+    u32f.u = 0xff012345;
+    test_checku(float2ufix(u32f.f, 0), 0, "float2ufix9d");
+    test_checku(float2ufix(u32f.f, 1), 0, "float2ufix9e");
+    test_checku(float2ufix(u32f.f, 2), 0, "float2ufix9f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    u32f.u = 0xff012345;
    test_checku(float2ufix(u32f.f, 0), 0, "float2ufix10a");
    test_checku(float2ufix(u32f.f, 1), 0, "float2ufix10b");
    test_checku(float2ufix(u32f.f, 2), 0, "float2ufix10c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 13]
```diff
@@ -245,11 +266,24 @@ int test() {
...
     test_checki64(float2fix64(-3.25f, 2), -13, "float2fix649");
     test_checki64(float2fix64(-3.0f, -1), -2, "float2fix6410"); // not very useful
+    u32f.u = 0x7f012345;
+    test_checki64(float2fix64(u32f.f, 0), INT64_MAX, "float2fix6411a");
+    test_checki64(float2fix64(u32f.f, 1), INT64_MAX, "float2fix6411b");
+    test_checki64(float2fix64(u32f.f, 2), INT64_MAX, "float2fix6411c");
+    u32f.u = 0xff012345;
+    test_checki64(float2fix64(u32f.f, 0), INT64_MIN, "float2fix6412d");
+    test_checki64(float2fix64(u32f.f, 1), INT64_MIN, "float2fix6412e");
+    test_checki64(float2fix64(u32f.f, 2), INT64_MIN, "float2fix6412f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    u32f.u = 0xff012345;
    test_checki64(float2fix64(u32f.f, 0), INT64_MIN, "float2fix6412a");
    test_checki64(float2fix64(u32f.f, 1), INT64_MIN, "float2fix6412b");
    test_checki64(float2fix64(u32f.f, 2), INT64_MIN, "float2fix6412c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 14]
```diff
@@ -258,9 +292,24 @@ int test() {
...
     test_checku64(float2ufix64(3.25f, 2), 13, "float2ufix647");
     test_checku64(float2ufix64(3.0f, -1), 1, "float2ufix648"); // not very useful
+    u32f.u = 0x7f012345;
+    test_checku64(float2ufix64(u32f.f, 0), UINT64_MAX, "float2ufix649a");
+    test_checku64(float2ufix64(u32f.f, 1), UINT64_MAX, "float2ufix649b");
+    test_checku64(float2ufix64(u32f.f, 2), UINT64_MAX, "float2ufix649c");
+    u32f.u = 0xff012345;
+    test_checku64(float2ufix64(u32f.f, 0), 0, "float2ufix6410d");
+    test_checku64(float2ufix64(u32f.f, 1), 0, "float2ufix6410e");
+    test_checku64(float2ufix64(u32f.f, 2), 0, "float2ufix6410f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    u32f.u = 0xff012345;
    test_checku64(float2ufix64(u32f.f, 0), 0, "float2ufix6410a");
    test_checku64(float2ufix64(u32f.f, 1), 0, "float2ufix6410b");
    test_checku64(float2ufix64(u32f.f, 2), 0, "float2ufix6410c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 15]
```diff
@@ -269,30 +318,47 @@ int test() {
...
     u32f.u = 0x7f012345;
-    test_checki(float2fix_z(u32f.f, 1), INT32_MAX, "float2fix_z12");
+    test_checki(float2fix_z(u32f.f, 0), INT32_MAX, "float2fix_z12a");
+    test_checki(float2fix_z(u32f.f, 1), INT32_MAX, "float2fix_z12b");
+    test_checki(float2fix_z(u32f.f, 2), INT32_MAX, "float2fix_z12c");
     u32f.u = 0xff012345;
-    test_checki(float2fix_z(u32f.f, 1), INT32_MIN, "float2fix_z13");
+    test_checki(float2fix_z(u32f.f, 0), INT32_MIN, "float2fix_z13d");
+    test_checki(float2fix_z(u32f.f, 1), INT32_MIN, "float2fix_z13e");
+    test_checki(float2fix_z(u32f.f, 2), INT32_MIN, "float2fix_z13f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    test_checki(float2fix_z(u32f.f, 0), INT32_MIN, "float2fix_z13a");
    test_checki(float2fix_z(u32f.f, 1), INT32_MIN, "float2fix_z13b");
    test_checki(float2fix_z(u32f.f, 2), INT32_MIN, "float2fix_z13c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 16]
```diff
@@ -269,30 +318,47 @@ int test() {
...
     u32f.u = 0x7f012345;
-    test_checku(float2ufix_z(u32f.f, 1), UINT32_MAX, "float2ufix_z9");
+    test_checku(float2ufix_z(u32f.f, 0), UINT32_MAX, "float2ufix_z9a");
+    test_checku(float2ufix_z(u32f.f, 1), UINT32_MAX, "float2ufix_z9b");
+    test_checku(float2ufix_z(u32f.f, 2), UINT32_MAX, "float2ufix_z9c");
     u32f.u = 0xff012345;
-    test_checku(float2ufix_z(u32f.f, 1), 0, "float2ufix_z10");
+    test_checku(float2ufix_z(u32f.f, 0), 0, "float2ufix_z10d");
+    test_checku(float2ufix_z(u32f.f, 1), 0, "float2ufix_z10e");
+    test_checku(float2ufix_z(u32f.f, 2), 0, "float2ufix_z10f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    test_checku(float2ufix_z(u32f.f, 0), 0, "float2ufix_z10a");
    test_checku(float2ufix_z(u32f.f, 1), 0, "float2ufix_z10b");
    test_checku(float2ufix_z(u32f.f, 2), 0, "float2ufix_z10c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 17]
```diff
@@ -301,22 +367,48 @@ int test() {
...
     test_checki64(float2fix64_z(-3.25f, 2), -13, "float2fix64_z9");
     test_checki64(float2fix64_z(-3.0f, -1), -1, "float2fix64_z10"); // not very useful
+    u32f.u = 0x7f012345;
+    test_checki64(float2fix64_z(u32f.f, 0), INT64_MAX, "float2fix64_z11a");
+    test_checki64(float2fix64_z(u32f.f, 1), INT64_MAX, "float2fix64_z11b");
+    test_checki64(float2fix64_z(u32f.f, 2), INT64_MAX, "float2fix64_z11c");
+    u32f.u = 0xff012345;
+    test_checki64(float2fix64_z(u32f.f, 0), INT64_MIN, "float2fix64_z12d");
+    test_checki64(float2fix64_z(u32f.f, 1), INT64_MIN, "float2fix64_z12e");
+    test_checki64(float2fix64_z(u32f.f, 2), INT64_MIN, "float2fix64_z12f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    u32f.u = 0xff012345;
    test_checki64(float2fix64_z(u32f.f, 0), INT64_MIN, "float2fix64_z12a");
    test_checki64(float2fix64_z(u32f.f, 1), INT64_MIN, "float2fix64_z12b");
    test_checki64(float2fix64_z(u32f.f, 2), INT64_MIN, "float2fix64_z12c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 18]
```diff
@@ -301,22 +367,48 @@ int test() {
...
-    test_checki64(float2ufix64_z(3.0f, -1), 1, "float2fuix64_z8"); // not very useful
+    test_checki64(float2ufix64_z(3.0f, -1), 1, "float2ufix64_z8"); // not very useful
+    u32f.u = 0x7f012345;
+    test_checku64(float2ufix64_z(u32f.f, 0), UINT64_MAX, "float2ufix64_z9a");
+    test_checku64(float2ufix64_z(u32f.f, 1), UINT64_MAX, "float2ufix64_z9b");
+    test_checku64(float2ufix64_z(u32f.f, 2), UINT64_MAX, "float2ufix64_z9c");
+    u32f.u = 0xff012345;
+    test_checku64(float2ufix64_z(u32f.f, 0), 0, "float2ufix64_z10d");
+    test_checku64(float2ufix64_z(u32f.f, 1), 0, "float2ufix64_z10e");
+    test_checku64(float2ufix64_z(u32f.f, 2), 0, "float2ufix64_z10f");
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    u32f.u = 0xff012345;
    test_checku64(float2ufix64_z(u32f.f, 0), 0, "float2ufix64_z10a");
    test_checku64(float2ufix64_z(u32f.f, 1), 0, "float2ufix64_z10b");
    test_checku64(float2ufix64_z(u32f.f, 2), 0, "float2ufix64_z10c");
```

File: test/pico_float_test/custom_float_funcs_test.c [hunk 19]
```diff
@@ -301,22 +367,48 @@ int test() {
...
     test_checku64(float2ufix64_z(INFINITY, 16), UINT64_MAX, "float2ufix64_z5");
+    test_checku64(float2ufix64_z(-INFINITY, 16), 0, "float2ufix64_z5b");
+    test_checku64(float2ufix64_z(INFINITY, -16), UINT64_MAX, "float2ufix64_z5c");
+    test_checku64(float2ufix64_z(-INFINITY, -16), 0, "float2ufix64_z5d");
+    test_checku64(float2ufix64_z(INFINITY, 0), UINT64_MAX, "float2ufix64_z5e");
+    test_checku64(float2ufix64_z(-INFINITY, 0), 0, "float2ufix64_z5f");
     test_checku64(float2ufix64_z(3.24999f, 2), 12, "float2ufix64_z6");
     test_checku64(float2ufix64_z(3.25f, 2), 13, "float2ufix64_z7");
-    test_checki64(float2ufix64_z(3.0f, -1), 1, "float2fuix64_z8"); // not very useful
+    test_checki64(float2ufix64_z(3.0f, -1), 1, "float2ufix64_z8"); // not very useful
```
Comment (lurch) [inline test/pico_float_test/custom_float_funcs_test.c]: Should the `test_checki64` here be `test_checku64`?

File: test/pico_float_test/custom_double_funcs_test.c [hunk 20]
```diff
@@ -250,11 +281,22 @@ int test() {
     test_checku64(double2ufix64(-INFINITY, 16), 0, "double2ufix645b");
     test_checku64(double2ufix64(INFINITY, -16), UINT64_MAX, "double2ufix645c");
     test_checku64(double2ufix64(-INFINITY, -16), 0, "double2ufix645d");
+    test_checku64(double2ufix64(INFINITY, 0), UINT64_MAX, "double2ufix645e");
+    test_checku64(double2ufix64(-INFINITY, 0), 0, "double2ufix645f");
     test_checku64(double2ufix64(3.24999, 2), 12, "double2ufix646");
     test_checku64(double2ufix64(3.25, 2), 13, "double2ufix647");
     test_checku64(double2ufix64(3.0, -1), 1, "double2ufix648"); // not very useful
     test_checki64(double2ufix64(0.0, 16), 0, "double2ufix649");
     test_checki64(double2ufix64(-0.0, 16), 0, "double2ufix6410");
```
Comment (lurch) [inline test/pico_float_test/custom_double_funcs_test.c]: Should these two lines be using `test_checku64`?

File: test/pico_float_test/custom_double_funcs_test.c [hunk 21]
```diff
@@ -250,11 +281,22 @@ int test() {
     test_checku64(double2ufix64(-INFINITY, 16), 0, "double2ufix645b");
     test_checku64(double2ufix64(INFINITY, -16), UINT64_MAX, "double2ufix645c");
     test_checku64(double2ufix64(-INFINITY, -16), 0, "double2ufix645d");
+    test_checku64(double2ufix64(INFINITY, 0), UINT64_MAX, "double2ufix645e");
+    test_checku64(double2ufix64(-INFINITY, 0), 0, "double2ufix645f");
     test_checku64(double2ufix64(3.24999, 2), 12, "double2ufix646");
     test_checku64(double2ufix64(3.25, 2), 13, "double2ufix647");
     test_checku64(double2ufix64(3.0, -1), 1, "double2ufix648"); // not very useful
     test_checki64(double2ufix64(0.0, 16), 0, "double2ufix649");
```
Comment (kilograham) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    test_checku64(double2ufix64(0.0, 16), 0, "double2ufix649");
```

File: test/pico_float_test/custom_double_funcs_test.c (hunk 20 above)
Comment (kilograham) [inline test/pico_float_test/custom_double_funcs_test.c]:
```suggestion
    test_checku64(double2ufix64(-0.0, 16), 0, "double2ufix6410");
```

File: test/pico_float_test/custom_float_funcs_test.c (hunk 19 above)
Comment (kilograham) [inline test/pico_float_test/custom_float_funcs_test.c]:
```suggestion
    test_checku64(float2ufix64_z(3.0f, -1), 1, "float2ufix64_z8"); // not very useful
```
