### PR TITLE
Fix unreliable writes to cyw43.

### LINKED ISSUE #2206: cyw43: dma_channel_abort interacting weirdly with chained DMA
I've been chasing an issue with wireless in our MicroPython builds, and after confirming that it's related to our DMA/PIO drivers for LED matrix displays came up with a reproduction: https://github.com/micropython/micropython/issues/16627

This reproduction reliably shows that setting up chained DMA (yes it's in MicroPython but my original code was a C module) upsets the cyw43 driver. This only happens on Pico 2 W/RP2350 (possibly related to DMA errata E5?) and the same (original C) code has worked on RP2040 since the original Pico W launched.

@MichaelBell rolled with this and found that adding `asm volatile (" nop\n nop\n nop " );` after calls to `dma_channel_abort` in `cyw43_bus_pio_spi.c` would somehow fix this, coming up with the following patch:

```diff
diff --git a/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c b/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
index bcc7284..1c6bd84 100644
--- a/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
+++ b/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
@@ -260,6 +260,7 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
         pio_sm_exec(bus_data->pio, bus_data->pio_sm, pio_encode_jmp(bus_data->pio_offset));
         dma_channel_abort(bus_data->dma_out);
         dma_channel_abort(bus_data->dma_in);
+        asm volatile (" nop\n nop\n nop " );
 
         dma_channel_config out_config = dma_channel_get_default_config(bus_data->dma_out);
         channel_config_set_bswap(&out_config, true);
@@ -301,6 +302,7 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
         pio_sm_exec(bus_data->pio, bus_data->pio_sm, pio_encode_out(pio_y, 32));
         pio_sm_exec(bus_data->pio, bus_data->pio_sm, pio_encode_jmp(bus_data->pio_offset));
         dma_channel_abort(bus_data->dma_out);
+        asm volatile (" nop\n nop\n nop " );
 
         dma_channel_config out_config = dma_channel_get_default_config(bus_data->dma_out);
         channel_config_set_bswap(&out_config, true);
```

We don't have a good sense for exactly what is happening, and it seems to vary between compilers (breaks as expected with GCC 14.2.1), but it's clear that it's a uniquely RP2350 problem and that a mitigation should be possible in Pico SDK.

### PR DESCRIPTION
**Pull request by peterharperuk**
We use a pio and dma to write to the cyw43 chip using spi. Normally you write an address and then read the data from that address, so the pio program does does a write then read.

If you just want to write data in the case of uploading firmware we use the fdebug_tx_stall flag to work out if the pio has stalled waiting to read data which will never arrive.

The theory is that this flag will also get set if the bus is busy. So we mistakenly think a write to cyw43 has completed.

Add a check for the dma irq as well.

Fixes #2206

### CODE REVIEW

File: src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c [hunk 1]
```diff
@@ -315,6 +316,12 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
             tight_loop_contents(); // todo timeout
         }
         __compiler_memory_barrier();
+
+        while (!(dma_hw->intr & 1u << bus_data->dma_out)) {
```
Comment (lurch) [inline src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:320]: Will this have to re-calculate `1u << bus_data->dma_out` each time around the loop? Perhaps it's worth calculating it once, before the `while` loop?

Comment (peterharperuk) [inline src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:320]: Should be able to wait for DMA to finish before waiting for stall?

File: src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c [hunk 2]
```diff
@@ -231,7 +231,7 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
         return CYW43_FAIL_FAST_CHECK(-CYW43_EINVAL);
     }
 
-    bus_data_t *bus_data = (bus_data_t *)self->bus_data;
+    volatile bus_data_t *bus_data = (bus_data_t *)self->bus_data;
```
Comment (peterharperuk) [inline src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:234]: Why is this needed?

**Comment by lurch** [comment]
Fixes #2206 #2152 #2123

File: src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c (hunk 1 above)
Comment (Wren6991) [reply src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:320]: The compiler can hoist simple loop-invariant code like this, unless you have done something weird like mark `bus_data` as `volatile`.

File: src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c (hunk 2 above)
Comment (lurch) [reply src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:234]: In some of the linked issues, it's mentioned that different compiler optimisation levels and/or different compiler versions can cause the bug to appear / not appear.

> That's odd for a stack variable.

Perhaps it means that this bug goes a bit deeper?

Comment (peterharperuk) [reply src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:234]: Yes, it fails without it. Something fishy is going on in release

Comment (peterharperuk) [reply src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:234]: If I add __attribute((noinline)) to the function it's ok (volatile not needed).

**Comment by Wren6991** [comment]
So if I understand the code correctly, these lines:

```c
        dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[bus_data->pio_sm], tx, tx_length / 4, true);

        uint32_t fdebug_tx_stall = 1u << (PIO_FDEBUG_TXSTALL_LSB + bus_data->pio_sm);
        bus_data->pio->fdebug = fdebug_tx_stall;
        pio_sm_set_enabled(bus_data->pio, bus_data->pio_sm, true);
        while (!(bus_data->pio->fdebug & fdebug_tx_stall)) {
            tight_loop_contents(); // todo timeout
        }
```

...are attempting to block until the state machine has consumed all of the TX data, before deconfiguring the state machine. The problem is that this code *also* detects the case where the TX FIFO has bottomed out for reasons other than all of the data having been transferred. In particular, it immediately falls through if no DMA write has yet taken place between the `dma_channel_configure()` call and the write to `bus_data->pio->fdebug`, which is really no time at all. We probably got away with this on RP2040 because the processors were slower relative to the DMA.

If we think that is the failure mode, then the most direct fix would be this one:

```patch
diff --git a/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c b/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
index bcc7284..a9f5970 100644
--- a/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
+++ b/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c
@@ -309,8 +309,10 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
         dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[bus_data->pio_sm], tx, tx_length / 4, true);
 
         uint32_t fdebug_tx_stall = 1u << (PIO_FDEBUG_TXSTALL_LSB + bus_data->pio_sm);
-        bus_data->pio->fdebug = fdebug_tx_stall;
         pio_sm_set_enabled(bus_data->pio, bus_data->pio_sm, true);
+
+        dma_channel_wait_for_finish_blocking(bus_data->dma_out);
+        bus_data->pio->fdebug = fdebug_tx_stall;
         while (!(bus_data->pio->fdebug & fdebug_tx_stall)) {
             tight_loop_contents(); // todo timeout
         }
```

So the steps are:

* wait for all data to be enqueued in TX FIFO
* **then** clear the TX stall flag, because we know it can no longer be caused by data not having been transferred
* then poll the TX stall flag to ensure the SM has completed

For me this also fixes the reproducer from #2123.

This also raises the question of why we are messing about with the DMA so much given this code is actually 100% blocking.

File: src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c (hunk 2 above)
Comment (Wren6991) [reply src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c:234]: I think this patch is still unsound because it checks things in the wrong order (see this comment https://github.com/raspberrypi/pico-sdk/pull/2209#issuecomment-2615466462).

It's likely that pushing the code around like this is adding delays and hiding symptoms.

**Comment by peterharperuk** [comment]
Yes, I agree. dma_channel_wait_for_finish_blocking in the right place works. Still something funny going on with the bus data but I think that's a separate problem.

**Comment by Wren6991** [comment]
> Still something funny going on with the bus data but I think that's a separate problem.

The fields you are accessing here are read-only after initialisation, so IMO this more likely to be a timing issue than anything to do with those particular accesses being volatile.

**Comment by peterharperuk** [comment]
> Still something funny going on with the bus data but I think that's a separate problem

False alarm I think. The code could do with a refactor. But I should probably avoid doing that here?

**Comment by lurch** [comment]
Minor nitpick, but given Luke's diagnosis above, should the "The theory is that this flag will also get set if the bus is busy. So we mistakenly think a write to cyw43 has completed." part be removed from the commit-message?

**Comment by peterharperuk** [comment]
> if the PIO is divided significantly

You mean this flag could be set by another state machine?

**Comment by kilograham** [comment]
i meant the clock, but either way, i think checking the address is better but i haven't dived deeply into this

**Comment by peterharperuk** [comment]
Ah, ok. I'll try checking the address.

**Review by kilograham — APPROVED** [review]

**Comment by matsobdev** [comment]
I'm just a simple man, don't much of that stuff, but will the last else if statement be reachable here: https://github.com/raspberrypi/pico-sdk/blob/3d746b3fa7ea7aa5ed80f66e47d54850e96da1f5/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L236-L328
given the fact that:
https://github.com/raspberrypi/pico-sdk/blob/3d746b3fa7ea7aa5ed80f66e47d54850e96da1f5/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L236
and:
https://github.com/raspberrypi/pico-sdk/blob/3d746b3fa7ea7aa5ed80f66e47d54850e96da1f5/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L322
Just asking, maybe it is suppose to be that way.

**Comment by peterharperuk** [comment]
No it won't.
