### PR TITLE
Fix minor unused/uninitialized warnings from G++

### LINKED ISSUE #1785: Minor GCC 12 unused/unitialized warnings in 2.0.0
GCC 12 is generating the following warnings on the 2.0.0 SDK release.  It's only cosmetic, but when a project builds with `-Werror` this will cause a failure.

````
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_timer/include/hardware/timer.h: In function 'uint hardware_alarm_get_irq_num(timer_hw_t*, uint)':
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_timer/include/hardware/timer.h:568:59: warning: unused parameter 'timer' [-Wunused-parameter]
  568 | static inline uint hardware_alarm_get_irq_num(timer_hw_t *timer, uint alarm_num) {
      |                                               ~~~~~~~~~~~~^~~~~
````

and

````
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_pio/include/hardware/pio.h: In function 'pio_sm_config pio_get_default_sm_config()':
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_pio/include/hardware/pio.h:650:25: warning: missing initializer for member 'pio_sm_config::execctrl' [-Wmissing-field-initializers]
  650 |     pio_sm_config c = {0};
      |                         ^
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_pio/include/hardware/pio.h:650:25: warning: missing initializer for member 'pio_sm_config::shiftctrl' [-Wmissing-field-initializers]
/home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_pio/include/hardware/pio.h:650:25: warning: missing initializer for member 'pio_sm_config::pinctrl' [-Wmissing-field-initializers]
````

### PR DESCRIPTION
**Pull request by earlephilhower**
Decorate an unused parameter in the timer API and fill in all structure elements in a PIO API call that generate warnings under GCC 12.

Fixes #1785

### CODE REVIEW

File: src/rp2_common/hardware_pio/include/hardware/pio.h [hunk 1]
```diff
@@ -647,7 +647,7 @@ static inline void sm_config_set_mov_status(pio_sm_config *c, enum pio_mov_statu
  * \return the default state machine configuration which can then be modified.
  */
 static inline pio_sm_config pio_get_default_sm_config(void) {
-    pio_sm_config c = {0};
+    pio_sm_config c = {0, 0, 0, 0};
```
Comment (peterharperuk) [inline src/rp2_common/hardware_pio/include/hardware/pio.h:650]: Might need an extra zero for when PICO_PIO_USE_GPIO_BASE is true

Comment (earlephilhower) [reply src/rp2_common/hardware_pio/include/hardware/pio.h:650]: Good catch, thanks.  I hadn't gotten into the config options quite yet.

**Comment by peterharperuk** [comment]
Looks good

File: src/rp2_common/hardware_timer/include/hardware/timer.h [hunk 2]
```diff
@@ -565,7 +565,8 @@ static inline uint timer_hardware_alarm_get_irq_num(__unused timer_hw_t *timer,
  * \param timer the timer instance
  * \param alarm_num the alarm number
  */
-static inline uint hardware_alarm_get_irq_num(timer_hw_t *timer, uint alarm_num) {
+static inline uint hardware_alarm_get_irq_num(__unused timer_hw_t *timer, uint alarm_num) {
```
Comment (kilograham) [inline src/rp2_common/hardware_timer/include/hardware/timer.h:568]: this is an actual bug, fixed in #1852

File: src/rp2_common/hardware_pio/include/hardware/pio.h [hunk 3]
```diff
@@ -647,9 +647,10 @@ static inline void sm_config_set_mov_status(pio_sm_config *c, enum pio_mov_statu
  * \return the default state machine configuration which can then be modified.
  */
 static inline pio_sm_config pio_get_default_sm_config(void) {
-    pio_sm_config c = {0};
-#if PICO_PIO_USE_GPIO_BASE
-    c.pinhi = -1;
+ #if PICO_PIO_USE_GPIO_BASE
```
Comment (kilograham) [inline src/rp2_common/hardware_pio/include/hardware/pio.h:650]: what is the warning what version of the compiler?

Comment (earlephilhower) [reply src/rp2_common/hardware_pio/include/hardware/pio.h:650]: `arm-none-eabi-gcc (GCC) 12.3.0` using `-Wall -Wextra`

File: src/rp2_common/hardware_timer/include/hardware/timer.h (hunk 2 above)
Comment (earlephilhower) [reply src/rp2_common/hardware_timer/include/hardware/timer.h]: Removed

File: src/rp2_common/hardware_pio/include/hardware/pio.h (hunk 3 above)
Comment (kilograham) [reply src/rp2_common/hardware_pio/include/hardware/pio.h:650]: Can you give the full output off `gcc --version` and/or say where you got it.

I'm tempted not to fix this as this is a compiler bug (and the fix is ugly/brittle), but if i can actually get an exact compiler which has this problem, i can see if it supports suppressing the warning

Comment (earlephilhower) [reply src/rp2_common/hardware_pio/include/hardware/pio.h:650]: I don't think this is a compiler issue so much as a C vs. C++ issue.

In C++ `{0}` will only set the 1st member of the structure to 0 because it's taking that as a positional initializer.  In C, IIRC, `{0}` will effectively `bzero` the struct, which might be where the confusion is stemming from.  You can include the SDK headers in C++ code, and when that happens the warning pops up.

This is with plain Ubuntu 20.04 GCC 9, not even the ARM x-compiler using a simple example to avoid a bunch of `-I`s.  Just a struct with >1 member being set to `{0}`.
````
earle@amd:~/Arduino/hardware/pico/rp2040$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

earle@amd:~/Arduino/hardware/pico/rp2040$ cat a.c
#include <stdio.h>
struct t {
    int a;
    int b;
};
void dummy() {
    struct t a = {0};
    printf("%d\n", a.b);
}
earle@amd:~/Arduino/hardware/pico/rp2040$ cp a.c a.cpp
earle@amd:~/Arduino/hardware/pico/rp2040$ gcc -Wall -Wextra -c  a.c
<note no warnings>
earle@amd:~/Arduino/hardware/pico/rp2040$ g++ -Wall -Wextra -c  a.c
a.c: In function ‘void dummy()’:
a.c:7:20: warning: missing initializer for member ‘t::b’ [-Wmissing-field-initializers]
    7 |     struct t a = {0};
      |       
````

**Comment by kilograham** [comment]
An ok - I had wondered if this was a c++ thing - the {0} is valid C but had seen reports of some versions (albeit old) reporting that exact message

**Comment by earlephilhower** [comment]
I had forgot about that simpler `{}` solution!  Updated with the change and I can confirm no warnings generated for it in the latest G++s.

**Comment by earlephilhower** [comment]
Done, thx!

**Review by kilograham — APPROVED** [review]
