### PR TITLE
Fix for cyw43 driver working with SMs other than 0

### LINKED ISSUE #1077: cyw43_driver only works with SM0
The cyw43_driver (see cyw43_bus_pio_spi.c) only supports SM0. It tries to play nice by allocating a free PIO and requesting a SM but if it gets an SM other than 0 it doesn't work.

The workaround is to make sure that you keep SM 0 free on a PIO for this driver.

In cyw43_bus_pio_spi.c (line 263) we have code like this ....
` dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[0], tx, tx_length / 4, true);`
Which is hardwiring the DMA to pio SM 0 fifo.

Have tried to fix, but not completely working yet :(

### PR DESCRIPTION
**Pull request by Lord-Lucan**
Fixes #1077

cyw43 driver is currently hard wired to use state machine (SM) 0. If a user program is allocated the same pio and SM 0 as cyw43 then the program will fail. Both cyw43 and user program will fall over each other trying to use SM 0.

This fix updates the cyw43 driver so that it doesn't assume that it has unique access to SM 0.

The cyw43 driver has a nod to playing fairly with the pio and sm but didn't quite make the required changes in cyw43_spi_transfer :)

### CODE REVIEW

**Review by kilograham — APPROVED** [review]

**Comment by kilograham** [comment]
can you please fix conflicts (presumably re-base onto newer `develop`)

File: src/rp2_common/cyw43_driver/cyw43_bus_pio_spi.c [hunk 1]
```diff
@@ -299,13 +299,13 @@ int cyw43_spi_transfer(cyw43_int_t *self, const uint8_t *tx, size_t tx_length, u
...
 
-        dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[0], tx, tx_length / 4, true);
+        dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[bus_data->pio_sm], tx, tx_length / 4, true);
 
-        bus_data->pio->fdebug = 1u << PIO_FDEBUG_TXSTALL_LSB;
-        pio_sm_set_enabled(bus_data->pio, 0, true);
-        while (!(bus_data->pio->fdebug & (1u << PIO_FDEBUG_TXSTALL_LSB))) {
+        bus_data->pio->fdebug = 1u << (PIO_FDEBUG_TXSTALL_LSB + bus_data->pio_sm);
+        pio_sm_set_enabled(bus_data->pio, bus_data->pio_sm, true);
+        while (!(bus_data->pio->fdebug & (1u << (PIO_FDEBUG_TXSTALL_LSB + bus_data->pio_sm)))) {
```
Comment (lurch) [inline src/rp2_common/cyw43_driver/cyw43_bus_pio_spi.c:308]: Does `(1u << (PIO_FDEBUG_TXSTALL_LSB + bus_data->pio_sm))` get collapsed into a compile-time constant, or does it get recalculated for every iteration round the loop?

**Comment by Lord-Lucan** [comment]
I've just rebased onto develop. Added a const variable for fDebug flag.

**Review by kilograham — APPROVED** [review]
